services:
  - type: web
    name: movie-recommender
    env: python
    buildCommand: "./setup.sh"
    startCommand: "streamlit run app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
